version: '3.8'
services:
  vtrust_app:
    build:
      context: .
      dockerfile: Dockerfile
    port:
      - 8000:8000
    volumes: 
      - .:/vtrust
    depends_on:
      - db
   
   db:
    image: mysql:5.7.22
    restart: always
    environment: 
      MYSQL_DATABASE: vtrust
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib//mysql
    ports:
      - 33066:3306
 